// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminsColumns holds the columns for the "admins" table.
	AdminsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeBytes, Size: 255},
		{Name: "created_date", Type: field.TypeTime},
	}
	// AdminsTable holds the schema information for the "admins" table.
	AdminsTable = &schema.Table{
		Name:       "admins",
		Columns:    AdminsColumns,
		PrimaryKey: []*schema.Column{AdminsColumns[0]},
	}
	// BoardsColumns holds the columns for the "boards" table.
	BoardsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "writer", Type: field.TypeString},
		{Name: "view", Type: field.TypeUint, Default: 0},
		{Name: "recommend", Type: field.TypeUint, Default: 0},
		{Name: "hot", Type: field.TypeBool, Default: false},
		{Name: "created_date", Type: field.TypeTime},
		{Name: "user_board", Type: field.TypeInt},
	}
	// BoardsTable holds the schema information for the "boards" table.
	BoardsTable = &schema.Table{
		Name:       "boards",
		Columns:    BoardsColumns,
		PrimaryKey: []*schema.Column{BoardsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "boards_users_board",
				Columns:    []*schema.Column{BoardsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// CaServersColumns holds the columns for the "ca_servers" table.
	CaServersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "user_caserver", Type: field.TypeInt},
	}
	// CaServersTable holds the schema information for the "ca_servers" table.
	CaServersTable = &schema.Table{
		Name:       "ca_servers",
		Columns:    CaServersColumns,
		PrimaryKey: []*schema.Column{CaServersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ca_servers_users_caserver",
				Columns:    []*schema.Column{CaServersColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeBytes, Size: 255},
		{Name: "description", Type: field.TypeString, Default: "none"},
		{Name: "created_date", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminsTable,
		BoardsTable,
		CaServersTable,
		UsersTable,
	}
)

func init() {
	BoardsTable.ForeignKeys[0].RefTable = UsersTable
	CaServersTable.ForeignKeys[0].RefTable = UsersTable
}
