// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kafka-go/ent/board"
	"github.com/kafka-go/ent/user"
)

// BoardCreate is the builder for creating a Board entity.
type BoardCreate struct {
	config
	mutation *BoardMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (bc *BoardCreate) SetTitle(s string) *BoardCreate {
	bc.mutation.SetTitle(s)
	return bc
}

// SetContent sets the "content" field.
func (bc *BoardCreate) SetContent(s string) *BoardCreate {
	bc.mutation.SetContent(s)
	return bc
}

// SetWriter sets the "writer" field.
func (bc *BoardCreate) SetWriter(s string) *BoardCreate {
	bc.mutation.SetWriter(s)
	return bc
}

// SetView sets the "view" field.
func (bc *BoardCreate) SetView(u uint) *BoardCreate {
	bc.mutation.SetView(u)
	return bc
}

// SetNillableView sets the "view" field if the given value is not nil.
func (bc *BoardCreate) SetNillableView(u *uint) *BoardCreate {
	if u != nil {
		bc.SetView(*u)
	}
	return bc
}

// SetRecommend sets the "recommend" field.
func (bc *BoardCreate) SetRecommend(u uint) *BoardCreate {
	bc.mutation.SetRecommend(u)
	return bc
}

// SetNillableRecommend sets the "recommend" field if the given value is not nil.
func (bc *BoardCreate) SetNillableRecommend(u *uint) *BoardCreate {
	if u != nil {
		bc.SetRecommend(*u)
	}
	return bc
}

// SetHot sets the "hot" field.
func (bc *BoardCreate) SetHot(b bool) *BoardCreate {
	bc.mutation.SetHot(b)
	return bc
}

// SetNillableHot sets the "hot" field if the given value is not nil.
func (bc *BoardCreate) SetNillableHot(b *bool) *BoardCreate {
	if b != nil {
		bc.SetHot(*b)
	}
	return bc
}

// SetCreatedDate sets the "created_date" field.
func (bc *BoardCreate) SetCreatedDate(t time.Time) *BoardCreate {
	bc.mutation.SetCreatedDate(t)
	return bc
}

// SetNillableCreatedDate sets the "created_date" field if the given value is not nil.
func (bc *BoardCreate) SetNillableCreatedDate(t *time.Time) *BoardCreate {
	if t != nil {
		bc.SetCreatedDate(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BoardCreate) SetID(u uint) *BoardCreate {
	bc.mutation.SetID(u)
	return bc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (bc *BoardCreate) SetUserID(id int) *BoardCreate {
	bc.mutation.SetUserID(id)
	return bc
}

// SetUser sets the "user" edge to the User entity.
func (bc *BoardCreate) SetUser(u *User) *BoardCreate {
	return bc.SetUserID(u.ID)
}

// Mutation returns the BoardMutation object of the builder.
func (bc *BoardCreate) Mutation() *BoardMutation {
	return bc.mutation
}

// Save creates the Board in the database.
func (bc *BoardCreate) Save(ctx context.Context) (*Board, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BoardCreate) SaveX(ctx context.Context) *Board {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BoardCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BoardCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BoardCreate) defaults() {
	if _, ok := bc.mutation.View(); !ok {
		v := board.DefaultView
		bc.mutation.SetView(v)
	}
	if _, ok := bc.mutation.Recommend(); !ok {
		v := board.DefaultRecommend
		bc.mutation.SetRecommend(v)
	}
	if _, ok := bc.mutation.Hot(); !ok {
		v := board.DefaultHot
		bc.mutation.SetHot(v)
	}
	if _, ok := bc.mutation.CreatedDate(); !ok {
		v := board.DefaultCreatedDate()
		bc.mutation.SetCreatedDate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BoardCreate) check() error {
	if _, ok := bc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Board.title"`)}
	}
	if v, ok := bc.mutation.Title(); ok {
		if err := board.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Board.title": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Board.content"`)}
	}
	if _, ok := bc.mutation.Writer(); !ok {
		return &ValidationError{Name: "writer", err: errors.New(`ent: missing required field "Board.writer"`)}
	}
	if v, ok := bc.mutation.Writer(); ok {
		if err := board.WriterValidator(v); err != nil {
			return &ValidationError{Name: "writer", err: fmt.Errorf(`ent: validator failed for field "Board.writer": %w`, err)}
		}
	}
	if _, ok := bc.mutation.View(); !ok {
		return &ValidationError{Name: "view", err: errors.New(`ent: missing required field "Board.view"`)}
	}
	if _, ok := bc.mutation.Recommend(); !ok {
		return &ValidationError{Name: "recommend", err: errors.New(`ent: missing required field "Board.recommend"`)}
	}
	if _, ok := bc.mutation.Hot(); !ok {
		return &ValidationError{Name: "hot", err: errors.New(`ent: missing required field "Board.hot"`)}
	}
	if _, ok := bc.mutation.CreatedDate(); !ok {
		return &ValidationError{Name: "created_date", err: errors.New(`ent: missing required field "Board.created_date"`)}
	}
	if _, ok := bc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Board.user"`)}
	}
	return nil
}

func (bc *BoardCreate) sqlSave(ctx context.Context) (*Board, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BoardCreate) createSpec() (*Board, *sqlgraph.CreateSpec) {
	var (
		_node = &Board{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(board.Table, sqlgraph.NewFieldSpec(board.FieldID, field.TypeUint))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.Title(); ok {
		_spec.SetField(board.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := bc.mutation.Content(); ok {
		_spec.SetField(board.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := bc.mutation.Writer(); ok {
		_spec.SetField(board.FieldWriter, field.TypeString, value)
		_node.Writer = value
	}
	if value, ok := bc.mutation.View(); ok {
		_spec.SetField(board.FieldView, field.TypeUint, value)
		_node.View = value
	}
	if value, ok := bc.mutation.Recommend(); ok {
		_spec.SetField(board.FieldRecommend, field.TypeUint, value)
		_node.Recommend = value
	}
	if value, ok := bc.mutation.Hot(); ok {
		_spec.SetField(board.FieldHot, field.TypeBool, value)
		_node.Hot = value
	}
	if value, ok := bc.mutation.CreatedDate(); ok {
		_spec.SetField(board.FieldCreatedDate, field.TypeTime, value)
		_node.CreatedDate = value
	}
	if nodes := bc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   board.UserTable,
			Columns: []string{board.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_board = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BoardCreateBulk is the builder for creating many Board entities in bulk.
type BoardCreateBulk struct {
	config
	err      error
	builders []*BoardCreate
}

// Save creates the Board entities in the database.
func (bcb *BoardCreateBulk) Save(ctx context.Context) ([]*Board, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Board, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BoardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BoardCreateBulk) SaveX(ctx context.Context) []*Board {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BoardCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BoardCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
