// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-board/ent/nonuser"
	"github.com/go-board/ent/predicate"
)

// NonUserDelete is the builder for deleting a NonUser entity.
type NonUserDelete struct {
	config
	hooks    []Hook
	mutation *NonUserMutation
}

// Where appends a list predicates to the NonUserDelete builder.
func (nud *NonUserDelete) Where(ps ...predicate.NonUser) *NonUserDelete {
	nud.mutation.Where(ps...)
	return nud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (nud *NonUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, nud.sqlExec, nud.mutation, nud.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (nud *NonUserDelete) ExecX(ctx context.Context) int {
	n, err := nud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (nud *NonUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(nonuser.Table, sqlgraph.NewFieldSpec(nonuser.FieldID, field.TypeInt))
	if ps := nud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, nud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	nud.mutation.done = true
	return affected, err
}

// NonUserDeleteOne is the builder for deleting a single NonUser entity.
type NonUserDeleteOne struct {
	nud *NonUserDelete
}

// Where appends a list predicates to the NonUserDelete builder.
func (nudo *NonUserDeleteOne) Where(ps ...predicate.NonUser) *NonUserDeleteOne {
	nudo.nud.mutation.Where(ps...)
	return nudo
}

// Exec executes the deletion query.
func (nudo *NonUserDeleteOne) Exec(ctx context.Context) error {
	n, err := nudo.nud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{nonuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (nudo *NonUserDeleteOne) ExecX(ctx context.Context) {
	if err := nudo.Exec(ctx); err != nil {
		panic(err)
	}
}
