// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-board/ent/nonuser"
	"github.com/go-board/ent/predicate"
)

// NonUserQuery is the builder for querying NonUser entities.
type NonUserQuery struct {
	config
	ctx        *QueryContext
	order      []nonuser.OrderOption
	inters     []Interceptor
	predicates []predicate.NonUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the NonUserQuery builder.
func (nuq *NonUserQuery) Where(ps ...predicate.NonUser) *NonUserQuery {
	nuq.predicates = append(nuq.predicates, ps...)
	return nuq
}

// Limit the number of records to be returned by this query.
func (nuq *NonUserQuery) Limit(limit int) *NonUserQuery {
	nuq.ctx.Limit = &limit
	return nuq
}

// Offset to start from.
func (nuq *NonUserQuery) Offset(offset int) *NonUserQuery {
	nuq.ctx.Offset = &offset
	return nuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (nuq *NonUserQuery) Unique(unique bool) *NonUserQuery {
	nuq.ctx.Unique = &unique
	return nuq
}

// Order specifies how the records should be ordered.
func (nuq *NonUserQuery) Order(o ...nonuser.OrderOption) *NonUserQuery {
	nuq.order = append(nuq.order, o...)
	return nuq
}

// First returns the first NonUser entity from the query.
// Returns a *NotFoundError when no NonUser was found.
func (nuq *NonUserQuery) First(ctx context.Context) (*NonUser, error) {
	nodes, err := nuq.Limit(1).All(setContextOp(ctx, nuq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{nonuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (nuq *NonUserQuery) FirstX(ctx context.Context) *NonUser {
	node, err := nuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first NonUser ID from the query.
// Returns a *NotFoundError when no NonUser ID was found.
func (nuq *NonUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nuq.Limit(1).IDs(setContextOp(ctx, nuq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{nonuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (nuq *NonUserQuery) FirstIDX(ctx context.Context) int {
	id, err := nuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single NonUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one NonUser entity is found.
// Returns a *NotFoundError when no NonUser entities are found.
func (nuq *NonUserQuery) Only(ctx context.Context) (*NonUser, error) {
	nodes, err := nuq.Limit(2).All(setContextOp(ctx, nuq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{nonuser.Label}
	default:
		return nil, &NotSingularError{nonuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (nuq *NonUserQuery) OnlyX(ctx context.Context) *NonUser {
	node, err := nuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only NonUser ID in the query.
// Returns a *NotSingularError when more than one NonUser ID is found.
// Returns a *NotFoundError when no entities are found.
func (nuq *NonUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = nuq.Limit(2).IDs(setContextOp(ctx, nuq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{nonuser.Label}
	default:
		err = &NotSingularError{nonuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (nuq *NonUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := nuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of NonUsers.
func (nuq *NonUserQuery) All(ctx context.Context) ([]*NonUser, error) {
	ctx = setContextOp(ctx, nuq.ctx, "All")
	if err := nuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*NonUser, *NonUserQuery]()
	return withInterceptors[[]*NonUser](ctx, nuq, qr, nuq.inters)
}

// AllX is like All, but panics if an error occurs.
func (nuq *NonUserQuery) AllX(ctx context.Context) []*NonUser {
	nodes, err := nuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of NonUser IDs.
func (nuq *NonUserQuery) IDs(ctx context.Context) (ids []int, err error) {
	if nuq.ctx.Unique == nil && nuq.path != nil {
		nuq.Unique(true)
	}
	ctx = setContextOp(ctx, nuq.ctx, "IDs")
	if err = nuq.Select(nonuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (nuq *NonUserQuery) IDsX(ctx context.Context) []int {
	ids, err := nuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (nuq *NonUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, nuq.ctx, "Count")
	if err := nuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, nuq, querierCount[*NonUserQuery](), nuq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (nuq *NonUserQuery) CountX(ctx context.Context) int {
	count, err := nuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (nuq *NonUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, nuq.ctx, "Exist")
	switch _, err := nuq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (nuq *NonUserQuery) ExistX(ctx context.Context) bool {
	exist, err := nuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the NonUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (nuq *NonUserQuery) Clone() *NonUserQuery {
	if nuq == nil {
		return nil
	}
	return &NonUserQuery{
		config:     nuq.config,
		ctx:        nuq.ctx.Clone(),
		order:      append([]nonuser.OrderOption{}, nuq.order...),
		inters:     append([]Interceptor{}, nuq.inters...),
		predicates: append([]predicate.NonUser{}, nuq.predicates...),
		// clone intermediate query.
		sql:  nuq.sql.Clone(),
		path: nuq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.NonUser.Query().
//		GroupBy(nonuser.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (nuq *NonUserQuery) GroupBy(field string, fields ...string) *NonUserGroupBy {
	nuq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &NonUserGroupBy{build: nuq}
	grbuild.flds = &nuq.ctx.Fields
	grbuild.label = nonuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.NonUser.Query().
//		Select(nonuser.FieldName).
//		Scan(ctx, &v)
func (nuq *NonUserQuery) Select(fields ...string) *NonUserSelect {
	nuq.ctx.Fields = append(nuq.ctx.Fields, fields...)
	sbuild := &NonUserSelect{NonUserQuery: nuq}
	sbuild.label = nonuser.Label
	sbuild.flds, sbuild.scan = &nuq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a NonUserSelect configured with the given aggregations.
func (nuq *NonUserQuery) Aggregate(fns ...AggregateFunc) *NonUserSelect {
	return nuq.Select().Aggregate(fns...)
}

func (nuq *NonUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range nuq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, nuq); err != nil {
				return err
			}
		}
	}
	for _, f := range nuq.ctx.Fields {
		if !nonuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if nuq.path != nil {
		prev, err := nuq.path(ctx)
		if err != nil {
			return err
		}
		nuq.sql = prev
	}
	return nil
}

func (nuq *NonUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*NonUser, error) {
	var (
		nodes = []*NonUser{}
		_spec = nuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*NonUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &NonUser{config: nuq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, nuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (nuq *NonUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := nuq.querySpec()
	_spec.Node.Columns = nuq.ctx.Fields
	if len(nuq.ctx.Fields) > 0 {
		_spec.Unique = nuq.ctx.Unique != nil && *nuq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, nuq.driver, _spec)
}

func (nuq *NonUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(nonuser.Table, nonuser.Columns, sqlgraph.NewFieldSpec(nonuser.FieldID, field.TypeInt))
	_spec.From = nuq.sql
	if unique := nuq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if nuq.path != nil {
		_spec.Unique = true
	}
	if fields := nuq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, nonuser.FieldID)
		for i := range fields {
			if fields[i] != nonuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := nuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := nuq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := nuq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := nuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (nuq *NonUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(nuq.driver.Dialect())
	t1 := builder.Table(nonuser.Table)
	columns := nuq.ctx.Fields
	if len(columns) == 0 {
		columns = nonuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if nuq.sql != nil {
		selector = nuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if nuq.ctx.Unique != nil && *nuq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range nuq.predicates {
		p(selector)
	}
	for _, p := range nuq.order {
		p(selector)
	}
	if offset := nuq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := nuq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// NonUserGroupBy is the group-by builder for NonUser entities.
type NonUserGroupBy struct {
	selector
	build *NonUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (nugb *NonUserGroupBy) Aggregate(fns ...AggregateFunc) *NonUserGroupBy {
	nugb.fns = append(nugb.fns, fns...)
	return nugb
}

// Scan applies the selector query and scans the result into the given value.
func (nugb *NonUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nugb.build.ctx, "GroupBy")
	if err := nugb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NonUserQuery, *NonUserGroupBy](ctx, nugb.build, nugb, nugb.build.inters, v)
}

func (nugb *NonUserGroupBy) sqlScan(ctx context.Context, root *NonUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(nugb.fns))
	for _, fn := range nugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*nugb.flds)+len(nugb.fns))
		for _, f := range *nugb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*nugb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nugb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// NonUserSelect is the builder for selecting fields of NonUser entities.
type NonUserSelect struct {
	*NonUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (nus *NonUserSelect) Aggregate(fns ...AggregateFunc) *NonUserSelect {
	nus.fns = append(nus.fns, fns...)
	return nus
}

// Scan applies the selector query and scans the result into the given value.
func (nus *NonUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, nus.ctx, "Select")
	if err := nus.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*NonUserQuery, *NonUserSelect](ctx, nus.NonUserQuery, nus, nus.inters, v)
}

func (nus *NonUserSelect) sqlScan(ctx context.Context, root *NonUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(nus.fns))
	for _, fn := range nus.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*nus.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := nus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
