// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/kafka-go/ent/admin"
	"github.com/kafka-go/ent/board"
	"github.com/kafka-go/ent/caserver"
	"github.com/kafka-go/ent/schema"
	"github.com/kafka-go/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescName is the schema descriptor for name field.
	adminDescName := adminFields[0].Descriptor()
	// admin.NameValidator is a validator for the "name" field. It is called by the builders before save.
	admin.NameValidator = adminDescName.Validators[0].(func(string) error)
	// adminDescPassword is the schema descriptor for password field.
	adminDescPassword := adminFields[1].Descriptor()
	// admin.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	admin.PasswordValidator = func() func([]byte) error {
		validators := adminDescPassword.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(password []byte) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// adminDescCreatedDate is the schema descriptor for created_date field.
	adminDescCreatedDate := adminFields[2].Descriptor()
	// admin.DefaultCreatedDate holds the default value on creation for the created_date field.
	admin.DefaultCreatedDate = adminDescCreatedDate.Default.(time.Time)
	boardFields := schema.Board{}.Fields()
	_ = boardFields
	// boardDescTitle is the schema descriptor for title field.
	boardDescTitle := boardFields[1].Descriptor()
	// board.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	board.TitleValidator = boardDescTitle.Validators[0].(func(string) error)
	// boardDescWriter is the schema descriptor for writer field.
	boardDescWriter := boardFields[3].Descriptor()
	// board.WriterValidator is a validator for the "writer" field. It is called by the builders before save.
	board.WriterValidator = boardDescWriter.Validators[0].(func(string) error)
	// boardDescView is the schema descriptor for view field.
	boardDescView := boardFields[4].Descriptor()
	// board.DefaultView holds the default value on creation for the view field.
	board.DefaultView = boardDescView.Default.(uint)
	// boardDescRecommend is the schema descriptor for recommend field.
	boardDescRecommend := boardFields[5].Descriptor()
	// board.DefaultRecommend holds the default value on creation for the recommend field.
	board.DefaultRecommend = boardDescRecommend.Default.(uint)
	// boardDescHot is the schema descriptor for hot field.
	boardDescHot := boardFields[6].Descriptor()
	// board.DefaultHot holds the default value on creation for the hot field.
	board.DefaultHot = boardDescHot.Default.(bool)
	// boardDescCreatedDate is the schema descriptor for created_date field.
	boardDescCreatedDate := boardFields[7].Descriptor()
	// board.DefaultCreatedDate holds the default value on creation for the created_date field.
	board.DefaultCreatedDate = boardDescCreatedDate.Default.(func() time.Time)
	caserverFields := schema.CaServer{}.Fields()
	_ = caserverFields
	// caserverDescName is the schema descriptor for name field.
	caserverDescName := caserverFields[0].Descriptor()
	// caserver.NameValidator is a validator for the "name" field. It is called by the builders before save.
	caserver.NameValidator = caserverDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.NameValidator is a validator for the "name" field. It is called by the builders before save.
	user.NameValidator = userDescName.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = func() func([]byte) error {
		validators := userDescPassword.Validators
		fns := [...]func([]byte) error{
			validators[0].(func([]byte) error),
			validators[1].(func([]byte) error),
		}
		return func(password []byte) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescDescription is the schema descriptor for description field.
	userDescDescription := userFields[2].Descriptor()
	// user.DefaultDescription holds the default value on creation for the description field.
	user.DefaultDescription = userDescDescription.Default.(string)
	// userDescCreatedDate is the schema descriptor for created_date field.
	userDescCreatedDate := userFields[3].Descriptor()
	// user.DefaultCreatedDate holds the default value on creation for the created_date field.
	user.DefaultCreatedDate = userDescCreatedDate.Default.(time.Time)
}
